name: Build Windows App

on:
  push:
    branches:
      - main
      - master
      - t_project
  pull_request:
    branches:
      - main
      - master
      - t_project
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Release (.exe)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja Build Tool
        run: choco install ninja -y

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.4'
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload ZIP Release (Folder)
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-zip
          path: build/windows/x64/runner/Release/